CC = gcc
LIBS = -lplush -lvga -lm
CFLAGS = -O2 -m486

# use this for slow computers to speed up framerate
CFLAGS += -DNO_RETRACE_WAIT
default: ex1 ex2 ex3 ex4

ex1.o: ex.h
ex2.o: ex.h
ex3.o: ex.h
ex4.o: ex.h

ex1: ex1.o
	$(CC) $(CFLAGS) -o ex1 ex1.o $(LIBS)
ex2: ex2.o
	$(CC) $(CFLAGS) -o ex2 ex2.o $(LIBS)
ex3: ex3.o
	$(CC) $(CFLAGS) -o ex3 ex3.o $(LIBS)
ex4: ex4.o
	$(CC) $(CFLAGS) -o ex4 ex4.o $(LIBS)

clean:
	-rm -f ex? ex?.o
